### ISSUE TITLE
Written legacy files not quite the correct format

### ISSUE THREAD

**Issue by trisyoungs** [disorderedmaterials/GudPy#476] opened 2024-01-09 13:44 UTC
While GudPy writes legacy (.txt) files compatible with the original GudrunGUI they are not _quite_ of the correct format.  Two things need to be changed in order to get them to load correctly in the original GudrunGUI:

1. Number of spaces between sample composition lines and the text comment (currently 8, needs to be 10)
2. Exponential amplitude and decay values - an unused third parameter was removed from read/write, but this is necessary for the file to load correctly. For example:
```
0  1          Exponential amplitude and decay [1/Å]
```
...should read...
```
0  1  0          Exponential amplitude and decay [1/Å]
```

**Comment by rhinoella** [comment] 2024-01-25 12:56
Duplicate of #477

**Closed as completed by rhinoella** 2024-01-25 12:56 UTC
